---
- hosts: localhost # ansible-playbook main.yml -K -e "git_name=<name> git_email=<email>"
  gather_facts: no
  vars: # libkrb5-dev
    pkgs: curl git keychain mlocate net-tools rsync software-properties-common telnet vim wget
    pips: pip #pywinrm pypsexec
  tasks:
  - apt: pkg={{ pkgs.split(' ') }} update_cache=yes
    become: yes
    tags: pkg_update
  - git_config: "{{ item }}"
    loop:
    - { name: "user.name", scope: global, value: "{{ git_name }}" }
    - { name: "user.email", scope: global, value: "{{ git_email }}" }
    - { name: "color.ui", scope: global, value: true }
  - git: repo=https://github.com/ralphie02/ws-setup.git dest=/tmp/ws-setup
    changed_when: no
  - copy: src=/tmp/ws-setup/ansible.cfg dest=~/.ansible.cfg force=no
  - include_tasks: /tmp/ws-setup/fzf.yml
  - include_tasks: /tmp/ws-setup/terminal.yml
  - include_tasks: /tmp/ws-setup/tmux.yml
  - include_tasks: /tmp/ws-setup/node.yml
    when: node_ver is defined or node is defined
  - include_tasks: /tmp/ws-setup/rbenv.yml
    when: rb_ver is defined or rails is defined
  - include_tasks: /tmp/ws-setup/rails.yml
    when: rails is defined
  - raw: rm -r /tmp/ws-setup
    changed_when: no
