---
- hosts: localhost # ansible-playbook <this file> -K -vvv
  gather_facts: no
  # connection: winrm
  vars:
    pkgs: curl git keychain libkrb5-dev mlocate net-tools rsync software-properties-common telnet
      vim wget
    pips: pip pywinrm pypsexec
#     # ansible_connection: ssh
#     # ansible_shell_type: cmd
#     # ansible_user: ralph
#     # ansible_password: "{{ ansible_become_pass }}"
#     # ansible_port: 5986
#     # ansible_connection: winrm
#     # ansible_winrm_transport: basic
#     # ansible_winrm_server_cert_validation: ignore
  tasks:
  - apt: pkg={{ pkgs.split(' ') }} update_cache=yes
    become: yes
  - git_config: "{{ item }}"
    loop:
    - { name: "user.name", scope: global, value: "{{ git_name }}" }
    - { name: "user.email", scope: global, value: "{{ git_email }}" }
    - { name: "color.ui", scope: global, value: true }
  - git: repo=https://github.com/ralphie02/ws-setup.git dest=/tmp/ws-setup
    changed_when: no
  - copy: src=/tmp/ws-setup/ansible.cfg dest=~/.ansible.cfg force=no
  - include_tasks: /tmp/ws-setup/terminal.yml
  - include_tasks: /tmp/ws-setup/tmux.yml
  - include_tasks: /tmp/ws-setup/fzf.yml
  - raw: rm -r /tmp/ws-setup
    changed_when: no

  # - name: Test the PsExec connection to the local system (target node) with your user
  #   # win_psexec:
  #   #   command: whoami.exe
  #   psexec:
  #     hostname: win.local
  #     connection_username: ralph
  #     connection_password: "{{ ansible_become_pass }}"
  #     executable: cmd.exe
  #     arguments: /c echo Hello World
  # # - win_command: whoami
  #   # connection: winrm
